# Generated by Django 6.0.4 on 2026-04-26 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_added_at_song_audio_file_song_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image_url',
        ),
        migrations.AddField(
            model_name='song',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='external_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку API'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено админом'),
        ),
        migrations.AddField(
            model_name='song',
            name='local_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка файла'),
        ),
        migrations.AddField(
            model_name='song',
            name='local_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/', verbose_name='MP3 Файл'),
        ),
        migrations.AddField(
            model_name='song',
            name='soundcloud_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на звук SoundCloud'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
