# Generated by Django 6.0.4 on 2026-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_audio_file_remove_song_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='song',
            name='external_image_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='song',
            name='local_cover',
        ),
        migrations.RemoveField(
            model_name='song',
            name='local_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='soundcloud_url',
        ),
        migrations.AddField(
            model_name='song',
            name='deezer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
