# Generated by Django 6.0.4 on 2026-04-30 00:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('user', 'deezer_id')},
        ),
    ]
